//! Lorehaven domain primitives.

pub mod anchor;
pub mod api_scopes;
pub mod blocking;
pub mod caps;
pub mod charging;
pub mod community;
pub mod content;
pub mod discovery;
pub mod document;
pub mod economy;
pub mod error;
pub mod events;
pub mod exports;
pub mod extension;
pub mod fairqueue;
pub mod feeds;
pub mod governance;
pub mod ids;
pub mod imports;
pub mod jobs;
pub mod library;
pub mod lending;
pub mod marketplace;
pub mod media;
pub mod monetization;
pub mod orphaning;
pub mod policy;
pub mod positivity;
pub mod query;
pub mod query_sql;
pub mod reading;
pub mod stats;
pub mod subscriptions;
pub mod taxonomy;
pub mod translation;
pub mod webhook;

pub use error::{AppError, ErrorCode, Result};
pub use ids::*;
