//! HTTP routes.

pub mod auth;
pub mod collaborators;
pub mod community;
pub mod discovery;
pub mod economy;
pub mod events;
pub mod exports;
pub mod external;
pub mod feedback;
pub mod governance;
pub mod health;
pub mod imports;
pub mod jobs;
pub mod library;
pub mod marketplace;
pub mod meta;
pub mod pseuds;
pub mod reading;
pub mod search;
pub mod settings;
pub mod taxonomy;
pub mod translation;
pub mod works;
