//! Build script for the server binary.
//!
//! Two jobs:
//!
//! 1. **Guarantee the embedded asset directory exists.** Spec §5 requires
//!    "a clean checkout builds" and "a frontend page loads from the Rust
//!    executable". The frontend bundle is generated by Vite into
//!    `frontend/dist`, which is not committed. `rust-embed` fails at compile
//!    time if the folder is missing, so we materialise a bootstrap page that
//!    tells the developer exactly what to run.
//!
//! 2. **Expose the build identity.** Git revision and build time are compiled
//!    in so `/health/live` and `/api/v1/meta` can report which build is
//!    actually running — the first question in any deployment incident.

use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    let manifest_dir = PathBuf::from(
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set by cargo"),
    );
    let frontend_dist = manifest_dir
        .parent()
        .and_then(Path::parent)
        .expect("crates/app lives two levels under the workspace root")
        .join("frontend")
        .join("dist");

    ensure_bootstrap_assets(&frontend_dist);

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", frontend_dist.display());

    // The build identity must change when the revision does, otherwise a
    // deployed binary keeps reporting the commit it was first built from.
    let git_dir = manifest_dir.join("../../.git");
    println!("cargo:rerun-if-changed={}", git_dir.join("HEAD").display());
    println!("cargo:rerun-if-changed={}", git_dir.join("refs").display());

    let git_revision = Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .current_dir(&manifest_dir)
        .output()
        .ok()
        .filter(|out| out.status.success())
        .map(|out| String::from_utf8_lossy(&out.stdout).trim().to_owned())
        .unwrap_or_else(|| "unknown".to_owned());

    let dirty = Command::new("git")
        .args(["status", "--porcelain"])
        .current_dir(&manifest_dir)
        .output()
        .ok()
        .filter(|out| out.status.success())
        .map(|out| !out.stdout.is_empty())
        .unwrap_or(false);

    println!("cargo:rustc-env=LOREHAVEN_GIT_REVISION={git_revision}");
    println!(
        "cargo:rustc-env=LOREHAVEN_GIT_DIRTY={}",
        if dirty { "dirty" } else { "clean" }
    );
    println!(
        "cargo:rustc-env=LOREHAVEN_BUILD_TIME={}",
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_secs())
            .unwrap_or(0)
    );
}

/// Create a placeholder bundle if the frontend has not been built yet.
fn ensure_bootstrap_assets(dist: &Path) {
    let index = dist.join("index.html");
    if index.exists() {
        return;
    }

    if std::fs::create_dir_all(dist).is_err() {
        // Let rust-embed report the real problem with a better message than we
        // could produce here.
        return;
    }

    let placeholder = r#"<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Lorehaven — frontend not built</title>
    <style>
      body { font-family: system-ui, sans-serif; max-width: 42rem; margin: 4rem auto; padding: 0 1.5rem; line-height: 1.6; }
      code { background: #eee; padding: 0.15rem 0.35rem; border-radius: 3px; }
    </style>
  </head>
  <body>
    <h1>Lorehaven is running</h1>
    <p>The backend is serving this placeholder because the frontend bundle was
       not present at compile time.</p>
    <p>Build it with:</p>
    <pre><code>cd frontend &amp;&amp; npm ci &amp;&amp; npm run build</code></pre>
    <p>Then rebuild the server so the assets are embedded.</p>
    <p>Backend health: <a href="/health/ready">/health/ready</a> &middot;
       API metadata: <a href="/api/v1/meta">/api/v1/meta</a></p>
  </body>
</html>
"#;

    let _ = std::fs::write(index, placeholder);
}
