//! Generates the embedded migration catalogue.
//!
//! Spec §4 requires database-specific migrations and warns against assuming
//! SQLite and PostgreSQL are interchangeable. So the two dialects get separate
//! directories, and this build script bakes both sets into the binary as
//! `include_str!` data.
//!
//! Embedding matters for operations: a self-hosted operator upgrades by
//! replacing one executable (spec §22, "install verified executable → migrate").
//! If migrations lived only on disk, the binary and the schema could drift.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set by cargo"),
    );
    let migrations_root = manifest_dir
        .parent()
        .and_then(Path::parent)
        .expect("crates/db lives two levels under the workspace root")
        .join("migrations");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR is set by cargo"));
    let out_file = out_dir.join("migration_catalogue.rs");

    let mut generated = String::from(
        "// @generated by crates/db/build.rs — do not edit.\n\
         //\n\
         // Each entry is (version, name, sql). Order is the directory order.\n\n",
    );

    for (dialect, const_name) in [
        ("sqlite", "SQLITE_MIGRATIONS"),
        ("postgres", "POSTGRES_MIGRATIONS"),
    ] {
        let dir = migrations_root.join(dialect);
        println!("cargo:rerun-if-changed={}", dir.display());

        let mut files = migration_files(&dir);
        files.sort();

        let _ = writeln!(
            generated,
            "/// {dialect} migrations, in application order.\n\
             pub static {const_name}: &[Migration] = &["
        );
        for (version, name, path) in &files {
            let _ = writeln!(
                generated,
                "    Migration {{ version: \"{version}\", name: \"{name}\", sql: include_str!(\"{}\") }},",
                path.display()
            );
        }
        generated.push_str("];\n\n");

        if files.is_empty() {
            // An empty set is legal while bootstrapping, but say so loudly so a
            // typo in the directory name cannot silently ship zero migrations.
            println!(
                "cargo:warning=no {dialect} migrations found in {}",
                dir.display()
            );
        }
    }

    std::fs::write(&out_file, generated).expect("write generated migration catalogue");
}

/// Collect `.sql` files, splitting `0001_identity.sql` into `("0001", "identity")`.
fn migration_files(dir: &Path) -> Vec<(String, String, PathBuf)> {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return Vec::new();
    };

    let mut files = Vec::new();
    for entry in entries.flatten() {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("sql") {
            continue;
        }
        let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else {
            continue;
        };
        let (version, name) = stem.split_once('_').unwrap_or((stem, stem));
        files.push((version.to_owned(), name.to_owned(), path));
    }
    files
}
