[package]
name = "lorehaven-domain"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Domain primitives for Lorehaven: identifiers, errors, policies"

[dependencies]
anyhow.workspace = true
crc32fast.workspace = true
base64.workspace = true
flate2.workspace = true
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
hmac.workspace = true
sha2.workspace = true
thiserror.workspace = true
time.workspace = true
uuid.workspace = true

[lints]
workspace = true
