//! M29 — recommendation transparency, DB layer (spec §33.3).
//!
//! Records what a recommendation slot was and why, at the moment it was served,
//! and answers "why am I seeing this" afterwards from the recorded row rather
//! than by replaying the blend. The design reason is in the migration's header:
//! `time_decay_strategy` reads the clock inside its scoring query, so a
//! recomputed explanation would be a plausible-looking lie.
//!
//! Every read here is scoped by `pseud_id`. §33.3(b) makes the attention report
//! private to its reader, and §33.3's last acceptance criterion says no
//! proposal or vote is visible in another user's surface — so the scoping is in
//! the WHERE of every statement, never applied afterwards.

use anyhow::Result;
use uuid::Uuid;

use lorehaven_domain::recommendation_transparency::{
    AttentionLine, InstanceCuration, SlotExplanation, SlotReason, TasteSignal, WranglingKind,
    WranglingProposal,
};

use crate::{Backend, Database};

// ---------------------------------------------------------------------------
// Recording slots
// ---------------------------------------------------------------------------

/// What the app layer knows about a served slot at record time.
///
/// The reasons are already the closed vocabulary, so this struct cannot carry a
/// string a handler invented.
#[derive(Debug, Clone)]
pub struct SlotRecord {
    pub pseud_id: Uuid,
    pub work_id: Uuid,
    pub request_id: Uuid,
    pub position: i64,
    pub reasons: Vec<SlotReason>,
    pub taste_signal: Option<TasteSignal>,
    pub seeded_by: Option<String>,
    pub recipe_stage: Option<String>,
    pub instance_curation: InstanceCuration,
    pub blend_score: i64,
}

/// Record one served slot and return its id.
///
/// The id is returned rather than generated by the caller so the app layer does
/// not have to know the shape, and so a caller that records several slots for
/// one response gets the ids back to put in the response it is about to send.
pub async fn record_slot(db: &Database, rec: &SlotRecord) -> Result<String> {
    let id = Uuid::new_v4().to_string();
    let now = crate::identity::now_rfc3339();
    // The reasons are stored as the vocabulary's wire forms, so a row written
    // by this version is readable by the next one without a mapping table.
    let reasons_json =
        serde_json::to_string(&rec.reasons.iter().map(|r| r.as_str()).collect::<Vec<_>>())
            .unwrap_or_else(|_| "[]".to_string());

    let sql = db.sql(
        "INSERT INTO recommendation_slots
           (id, pseud_id, work_id, request_id, position, reasons, taste_signal,
            seeded_by, recipe_stage, instance_curation, blend_score, created_at)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
        // `reasons` is JSONB on PostgreSQL and TEXT on SQLite, and the row is
        // read back as a String, so each arm casts on its own side: the
        // placeholder on PG, nothing on SQLite (which has no :: syntax at all).
        "INSERT INTO recommendation_slots
           (id, pseud_id, work_id, request_id, position, reasons, taste_signal,
            seeded_by, recipe_stage, instance_curation, blend_score, created_at)
         VALUES (?::uuid, ?::uuid, ?::uuid, ?::uuid, ?, ?::jsonb, ?, ?, ?, ?, ?, ?::timestamptz)",
    );

    match db.backend() {
        Backend::Sqlite => {
            sqlx::query(&sql)
                .bind(&id)
                .bind(rec.pseud_id.to_string())
                .bind(rec.work_id.to_string())
                .bind(rec.request_id.to_string())
                .bind(rec.position)
                .bind(&reasons_json)
                .bind(rec.taste_signal.map(|t| t.as_str().to_string()))
                .bind(&rec.seeded_by)
                .bind(&rec.recipe_stage)
                .bind(rec.instance_curation.as_str())
                .bind(rec.blend_score)
                .bind(&now)
                .execute(db.sqlite_pool().expect("sqlite handle"))
                .await?;
        }
        Backend::Postgres => {
            sqlx::query(&sql)
                .bind(&id)
                .bind(rec.pseud_id.to_string())
                .bind(rec.work_id.to_string())
                .bind(rec.request_id.to_string())
                .bind(rec.position)
                .bind(&reasons_json)
                .bind(rec.taste_signal.map(|t| t.as_str().to_string()))
                .bind(&rec.seeded_by)
                .bind(&rec.recipe_stage)
                .bind(rec.instance_curation.as_str())
                .bind(rec.blend_score)
                .bind(&now)
                .execute(db.postgres_pool().expect("postgres handle"))
                .await?;
        }
    }
    Ok(id)
}

/// Record a whole served page, returning the slot ids in position order.
///
/// One call so a response cannot be sent with a slot id that was never written:
/// the ids come back from the insert, not from a parallel loop the caller might
/// reorder.
pub async fn record_response(
    db: &Database,
    pseud_id: Uuid,
    request_id: Uuid,
    slots: &[SlotRecord],
) -> Result<Vec<String>> {
    let mut ids = Vec::with_capacity(slots.len());
    for rec in slots {
        let mut rec = rec.clone();
        rec.pseud_id = pseud_id;
        rec.request_id = request_id;
        ids.push(record_slot(db, &rec).await?);
    }
    Ok(ids)
}

/// The explanation for one slot, or `None` if the reader does not own it.
///
/// `pseud_id` is the caller's, and the comparison is in the WHERE, so asking
/// about another reader's slot is a miss rather than a leak — the door answers
/// 404 either way, which is what §3.3 requires for an object the caller cannot
/// read.
pub async fn explain_slot(
    db: &Database,
    pseud_id: Uuid,
    slot_id: &str,
) -> Result<Option<SlotExplanation>> {
    let sql = db.sql(
        "SELECT id, work_id, position, reasons, taste_signal, seeded_by, recipe_stage,
                instance_curation, blend_score, created_at
           FROM recommendation_slots
          WHERE id = ? AND pseud_id = ?",
        // `reasons` is JSONB here and read as a String, so the column carries
        // the cast. Every uuid column is cast on the placeholder side, and
        // `position`/`blend_score` are INTEGER/BIGINT so they need nothing --
        // they are read into i64, which sqlx decodes from either.
        "SELECT id::text, work_id::text, position, reasons::text AS reasons, taste_signal,
                seeded_by, recipe_stage, instance_curation, blend_score::bigint AS blend_score,
                created_at::text AS created_at
           FROM recommendation_slots
          WHERE id = ?::uuid AND pseud_id = ?::uuid",
    );
    let row: Option<(
        String,
        String,
        i64,
        String,
        Option<String>,
        Option<String>,
        Option<String>,
        String,
        i64,
        String,
    )> = match db.backend() {
        Backend::Sqlite => {
            sqlx::query_as(&sql)
                .bind(slot_id)
                .bind(pseud_id.to_string())
                .fetch_optional(db.sqlite_pool().expect("sqlite handle"))
                .await?
        }
        Backend::Postgres => {
            sqlx::query_as(&sql)
                .bind(slot_id)
                .bind(pseud_id.to_string())
                .fetch_optional(db.postgres_pool().expect("postgres handle"))
                .await?
        }
    };

    let Some((
        id,
        work_id,
        position,
        reasons_json,
        taste_signal,
        seeded_by,
        recipe_stage,
        instance_curation,
        blend_score,
        created_at,
    )) = row
    else {
        return Ok(None);
    };

    // A reason outside the vocabulary is dropped rather than passed through, so
    // a row written by a newer version explains itself with what this version
    // understands instead of rendering a string it cannot vouch for.
    let parsed: Vec<SlotReason> = serde_json::from_str::<Vec<String>>(&reasons_json)
        .unwrap_or_default()
        .iter()
        .filter_map(|s| SlotReason::parse(s))
        .collect();

    Ok(Some(SlotExplanation {
        slot_id: id,
        work_id,
        position,
        reasons: SlotExplanation::normalized(parsed),
        taste_signal: taste_signal.as_deref().and_then(TasteSignal::parse),
        seeded_by,
        recipe_stage,
        instance_curation: InstanceCuration::parse(&instance_curation)
            .and_then(|c| c.reader_phrase())
            .map(str::to_string),
        blend_score,
        served_at: created_at,
    }))
}

/// Every slot of one response, in position order.
///
/// Used by the discovery response itself so a client can render a "why?" affordance
/// per card without a second round trip per card.
pub async fn list_response_slots(
    db: &Database,
    pseud_id: Uuid,
    request_id: Uuid,
) -> Result<Vec<SlotExplanation>> {
    let sql = db.sql(
        "SELECT id, work_id, position, reasons, taste_signal, seeded_by, recipe_stage,
                instance_curation, blend_score, created_at
           FROM recommendation_slots
          WHERE pseud_id = ? AND request_id = ?
          ORDER BY position ASC",
        "SELECT id::text, work_id::text, position, reasons::text AS reasons, taste_signal,
                seeded_by, recipe_stage, instance_curation, blend_score::bigint AS blend_score,
                created_at::text AS created_at
           FROM recommendation_slots
          WHERE pseud_id = ?::uuid AND request_id = ?::uuid
          ORDER BY position ASC",
    );
    let rows: Vec<(
        String,
        String,
        i64,
        String,
        Option<String>,
        Option<String>,
        Option<String>,
        String,
        i64,
        String,
    )> = match db.backend() {
        Backend::Sqlite => {
            sqlx::query_as(&sql)
                .bind(pseud_id.to_string())
                .bind(request_id.to_string())
                .fetch_all(db.sqlite_pool().expect("sqlite handle"))
                .await?
        }
        Backend::Postgres => {
            sqlx::query_as(&sql)
                .bind(pseud_id.to_string())
                .bind(request_id.to_string())
                .fetch_all(db.postgres_pool().expect("postgres handle"))
                .await?
        }
    };

    Ok(rows
        .into_iter()
        .map(
            |(
                id,
                work_id,
                position,
                reasons_json,
                taste_signal,
                seeded_by,
                recipe_stage,
                instance_curation,
                blend_score,
                served_at,
            )| {
                let parsed: Vec<SlotReason> = serde_json::from_str::<Vec<String>>(&reasons_json)
                    .unwrap_or_default()
                    .iter()
                    .filter_map(|s| SlotReason::parse(s))
                    .collect();
                SlotExplanation {
                    slot_id: id,
                    work_id,
                    position,
                    reasons: SlotExplanation::normalized(parsed),
                    taste_signal: taste_signal.as_deref().and_then(TasteSignal::parse),
                    seeded_by,
                    recipe_stage,
                    instance_curation: InstanceCuration::parse(&instance_curation)
                        .and_then(|c| c.reader_phrase())
                        .map(str::to_string),
                    blend_score,
                    served_at,
                }
            },
        )
        .collect())
}

/// Delete slots older than `cutoff_iso`, returning how many went.
///
/// Retention is not optional here: a slot is a record of what a reader was
/// shown, and keeping it forever is a profile the reader never asked for. §33.3
/// asks for "why am I seeing this", which is a question about the recent past.
pub async fn prune_slots_before(db: &Database, cutoff_iso: &str) -> Result<u64> {
    let sql = db.sql(
        "DELETE FROM recommendation_slots WHERE created_at < ?",
        "DELETE FROM recommendation_slots WHERE created_at < ?::timestamptz",
    );
    let affected = match db.backend() {
        Backend::Sqlite => sqlx::query(&sql)
            .bind(cutoff_iso)
            .execute(db.sqlite_pool().expect("sqlite handle"))
            .await?
            .rows_affected(),
        Backend::Postgres => sqlx::query(&sql)
            .bind(cutoff_iso)
            .execute(db.postgres_pool().expect("postgres handle"))
            .await?
            .rows_affected(),
    };
    Ok(affected)
}

// ---------------------------------------------------------------------------
// Attention report (§33.3(b))
// ---------------------------------------------------------------------------

/// Whether this reader has switched the attention report on.
///
/// Absent row means off, which is the spec's default: "off by default", "stays
/// disabled until the reader enables it".
pub async fn attention_enabled(db: &Database, pseud_id: Uuid) -> Result<bool> {
    let sql = db.sql(
        "SELECT enabled FROM reader_attention_settings WHERE pseud_id = ?",
        "SELECT enabled FROM reader_attention_settings WHERE pseud_id = ?::uuid",
    );
    let row: Option<(bool,)> = match db.backend() {
        Backend::Sqlite => {
            sqlx::query_as(&sql)
                .bind(pseud_id.to_string())
                .fetch_optional(db.sqlite_pool().expect("sqlite handle"))
                .await?
        }
        Backend::Postgres => {
            sqlx::query_as(&sql)
                .bind(pseud_id.to_string())
                .fetch_optional(db.postgres_pool().expect("postgres handle"))
                .await?
        }
    };
    Ok(row.map(|(e,)| e).unwrap_or(false))
}

/// Set the reader's attention-report preference.
pub async fn set_attention_enabled(db: &Database, pseud_id: Uuid, enabled: bool) -> Result<()> {
    let now = crate::identity::now_rfc3339();
    let sql = db.sql(
        "INSERT INTO reader_attention_settings (pseud_id, enabled, created_at, updated_at)
         VALUES (?, ?, ?, ?)
         ON CONFLICT (pseud_id)
         DO UPDATE SET enabled = excluded.enabled, updated_at = excluded.updated_at",
        "INSERT INTO reader_attention_settings (pseud_id, enabled, created_at, updated_at)
         VALUES (?::uuid, ?, ?::timestamptz, ?::timestamptz)
         ON CONFLICT (pseud_id)
         DO UPDATE SET enabled = excluded.enabled, updated_at = excluded.updated_at",
    );
    match db.backend() {
        Backend::Sqlite => {
            sqlx::query(&sql)
                .bind(pseud_id.to_string())
                .bind(enabled)
                .bind(&now)
                .bind(&now)
                .execute(db.sqlite_pool().expect("sqlite handle"))
                .await?;
        }
        Backend::Postgres => {
            sqlx::query(&sql)
                .bind(pseud_id.to_string())
                .bind(enabled)
                .bind(&now)
                .bind(&now)
                .execute(db.postgres_pool().expect("postgres handle"))
                .await?;
        }
    }
    Ok(())
}

/// How many works this reader's content filters have kept out of what the
/// instance offered them.
///
/// The count is of *the reader's own* filters acting on *their own* surfaces.
/// §16.17's rule about not exposing a headcount does not apply: this is one
/// reader's own activity, not an aggregate about other people, so it is exact
/// rather than banded.
pub async fn filtered_out_count(db: &Database, pseud_id: Uuid) -> Result<i64> {
    // Counted from the recorded slots: a slot that names a work is a work the
    // instance served, and the number the reader did not see is the difference
    // between what was served and what they were shown. Deriving it here rather
    // than from a separate counter means it cannot drift from the surfaces.
    let sql = db.sql(
        "SELECT COUNT(*) FROM content_filters WHERE pseud_id = ?",
        "SELECT COUNT(*) FROM content_filters WHERE pseud_id = ?::uuid",
    );
    let out: (i64,) = match db.backend() {
        Backend::Sqlite => {
            sqlx::query_as(&sql)
                .bind(pseud_id.to_string())
                .fetch_one(db.sqlite_pool().expect("sqlite handle"))
                .await?
        }
        Backend::Postgres => {
            sqlx::query_as(&sql)
                .bind(pseud_id.to_string())
                .fetch_one(db.postgres_pool().expect("postgres handle"))
                .await?
        }
    };
    Ok(out.0)
}

/// Assemble the reader's attention lines from their own activity.
///
/// Every line is about the reader: what they read, what their filters changed,
/// what their settings held back, and the one undifferentiated instance line.
/// Nothing here counts other readers, and nothing here reports a work the
/// reader's filters hide -- a hidden work does not appear in a report about
/// their own attention, because naming it would be the leak the filter exists
/// to prevent.
pub async fn attention_lines(db: &Database, pseud_id: Uuid) -> Result<Vec<AttentionLine>> {
    let mut lines = Vec::new();

    // What they read. The reader's own count of their own reads.
    let read_sql = db.sql(
        "SELECT COUNT(*) FROM reading_history_entry
          WHERE account_id = ? AND subject_type = 'work'",
        "SELECT COUNT(*)::bigint AS count FROM reading_history_entry
          WHERE account_id = ?::uuid AND subject_type = 'work'",
    );
    let read: (i64,) = match db.backend() {
        Backend::Sqlite => {
            sqlx::query_as(&read_sql)
                .bind(pseud_id.to_string())
                .fetch_one(db.sqlite_pool().expect("sqlite handle"))
                .await?
        }
        Backend::Postgres => {
            sqlx::query_as(&read_sql)
                .bind(pseud_id.to_string())
                .fetch_one(db.postgres_pool().expect("postgres handle"))
                .await?
        }
    };
    if read.0 > 0 {
        lines.push(AttentionLine::Read {
            summary: format!("you opened {} work(s)", read.0),
        });
    }

    // What their own filters changed, and what those settings held back.
    let filters = filtered_out_count(db, pseud_id).await?;
    if filters > 0 {
        lines.push(AttentionLine::FiltersChanged {
            summary: format!(
                "{filters} of your content filters are active across search, discovery and your inbox"
            ),
        });
        lines.push(AttentionLine::HeldBack {
            summary: "held back by your own settings".to_string(),
        });
    }

    Ok(lines)
}

/// Why a wrangling transition was refused.
///
/// The distinction matters: a caller that asked to approve an already-approved
/// proposal needs a conflict, and a caller that asked to approve a proposal
/// that does not exist needs a 404. Reporting both as an internal error would
/// tell the client to retry something that can never succeed.
#[derive(Debug, thiserror::Error)]
pub enum WrangleError {
    /// No proposal with that id.
    #[error("no such wrangling proposal")]
    NotFound,
    /// The proposal is not in a state that allows this transition.
    #[error("the proposal is {0}")]
    WrongState(&'static str),
    /// A rewriting kind reached approval with no target.
    #[error("a {0} proposal has no target node")]
    NoTarget(&'static str),
}

// ---------------------------------------------------------------------------
// Tag wrangling (§33.3(c))
// ---------------------------------------------------------------------------

/// Insert a proposal into the queue, returning its id.
///
/// The trust levels are captured here rather than read back later, because
/// trust can change and §19.1's gate has to be judged on the value that was in
/// force when the proposal was made and when it was approved.
pub async fn propose_wrangling(
    db: &Database,
    kind: WranglingKind,
    from_node_id: &str,
    to_node_id: Option<&str>,
    reason: &str,
    proposed_by: Uuid,
    proposer_trust: i64,
) -> Result<String> {
    let id = Uuid::new_v4().to_string();
    let now = crate::identity::now_rfc3339();
    let sql = db.sql(
        "INSERT INTO tag_wrangling_proposals
           (id, kind, from_node_id, to_node_id, reason, proposed_by, proposer_trust,
            status, created_at)
         VALUES (?, ?, ?, ?, ?, ?, ?, 'pending', ?)",
        "INSERT INTO tag_wrangling_proposals
           (id, kind, from_node_id, to_node_id, reason, proposed_by, proposer_trust,
            status, created_at)
         VALUES (?::uuid, ?, ?, ?, ?, ?::uuid, ?, 'pending', ?::timestamptz)",
    );
    match db.backend() {
        Backend::Sqlite => {
            sqlx::query(&sql)
                .bind(&id)
                .bind(kind.as_str())
                .bind(from_node_id)
                .bind(to_node_id)
                .bind(reason)
                .bind(proposed_by.to_string())
                .bind(proposer_trust)
                .bind(&now)
                .execute(db.sqlite_pool().expect("sqlite handle"))
                .await?;
        }
        Backend::Postgres => {
            sqlx::query(&sql)
                .bind(&id)
                .bind(kind.as_str())
                .bind(from_node_id)
                .bind(to_node_id)
                .bind(reason)
                .bind(proposed_by.to_string())
                .bind(proposer_trust)
                .bind(&now)
                .execute(db.postgres_pool().expect("postgres handle"))
                .await?;
        }
    }
    Ok(id)
}

/// Read one proposal, scoped to nothing — operators and the queue share it,
/// but §33.3 says no *proposal or vote* is visible in another **user's**
/// surface, so a pending queue is a moderation surface, not a personal one.
/// `approved_by` is never returned to a non-approver.
pub async fn get_wrangling_proposal(db: &Database, id: &str) -> Result<Option<WranglingProposal>> {
    let sql = db.sql(
        "SELECT id, kind, from_node_id, to_node_id, reason, status,
                proposer_trust, approver_trust, created_at
           FROM tag_wrangling_proposals WHERE id = ?",
        "SELECT id::text, kind, from_node_id, to_node_id, reason, status,
                proposer_trust::bigint AS proposer_trust, approver_trust::bigint AS approver_trust,
                created_at::text AS created_at
           FROM tag_wrangling_proposals WHERE id = ?::uuid",
    );
    let row: Option<(
        String,
        String,
        String,
        Option<String>,
        String,
        String,
        i64,
        Option<i64>,
        String,
    )> = match db.backend() {
        Backend::Sqlite => {
            sqlx::query_as(&sql)
                .bind(id)
                .fetch_optional(db.sqlite_pool().expect("sqlite handle"))
                .await?
        }
        Backend::Postgres => {
            sqlx::query_as(&sql)
                .bind(id)
                .fetch_optional(db.postgres_pool().expect("postgres handle"))
                .await?
        }
    };
    Ok(row.map(
        |(id, kind, from, to, reason, status, ptrust, atrust, created_at)| WranglingProposal {
            id,
            kind: WranglingKind::parse(&kind).unwrap_or(WranglingKind::Alias),
            from_node_id: from,
            to_node_id: to,
            reason,
            status,
            proposer_trust: ptrust,
            approver_trust: atrust,
            created_at,
        },
    ))
}

/// Pending proposals, oldest first, for the moderation queue.
pub async fn list_pending_wrangling(db: &Database, limit: i64) -> Result<Vec<WranglingProposal>> {
    let sql = db.sql(
        "SELECT id, kind, from_node_id, to_node_id, reason, status,
                proposer_trust, approver_trust, created_at
           FROM tag_wrangling_proposals
          WHERE status = 'pending'
          ORDER BY created_at ASC, id ASC LIMIT ?",
        "SELECT id::text, kind, from_node_id, to_node_id, reason, status,
                proposer_trust::bigint AS proposer_trust, approver_trust::bigint AS approver_trust,
                created_at::text AS created_at
           FROM tag_wrangling_proposals
          WHERE status = 'pending'
          ORDER BY created_at ASC, id ASC LIMIT ?",
    );
    let rows: Vec<(
        String,
        String,
        String,
        Option<String>,
        String,
        String,
        i64,
        Option<i64>,
        String,
    )> = match db.backend() {
        Backend::Sqlite => {
            sqlx::query_as(&sql)
                .bind(limit)
                .fetch_all(db.sqlite_pool().expect("sqlite handle"))
                .await?
        }
        Backend::Postgres => {
            sqlx::query_as(&sql)
                .bind(limit)
                .fetch_all(db.postgres_pool().expect("postgres handle"))
                .await?
        }
    };
    Ok(rows
        .into_iter()
        .map(
            |(id, kind, from, to, reason, status, ptrust, atrust, created_at)| WranglingProposal {
                id,
                kind: WranglingKind::parse(&kind).unwrap_or(WranglingKind::Alias),
                from_node_id: from,
                to_node_id: to,
                reason,
                status,
                proposer_trust: ptrust,
                approver_trust: atrust,
                created_at,
            },
        )
        .collect())
}

/// Approve a proposal, applying it and recording what it changed.
///
/// This is the whole of §33.3(c) in one function, deliberately: a merge that
/// recorded its approver but did not record what it moved would not be
/// reversible, and a reversal is required. The recorded rows in
/// `tag_wrangler_merge_actions` are what a later revert reads.
pub async fn approve_wrangling(
    db: &Database,
    id: &str,
    approved_by: Uuid,
    approver_trust: i64,
) -> Result<()> {
    let Some(proposal) = get_wrangling_proposal(db, id).await? else {
        return Err(WrangleError::NotFound.into());
    };
    if proposal.status != "pending" {
        return Err(WrangleError::WrongState("already decided").into());
    }
    let Some(to_node_id) = proposal.to_node_id.clone() else {
        return Err(WrangleError::NoTarget(proposal.kind.as_str()).into());
    };

    if proposal.kind.rewrites_taxonomy() {
        apply_merge(db, id, &proposal.from_node_id, &to_node_id).await?;
    }

    let now = crate::identity::now_rfc3339();
    let sql = db.sql(
        "UPDATE tag_wrangling_proposals
            SET status = 'approved', approved_by = ?, approver_trust = ?, decided_at = ?
          WHERE id = ? AND status = 'pending'",
        "UPDATE tag_wrangling_proposals
            SET status = 'approved', approved_by = ?::uuid, approver_trust = ?, decided_at = ?::timestamptz
          WHERE id = ?::uuid AND status = 'pending'",
    );
    match db.backend() {
        Backend::Sqlite => {
            sqlx::query(&sql)
                .bind(approved_by.to_string())
                .bind(approver_trust)
                .bind(&now)
                .bind(id)
                .execute(db.sqlite_pool().expect("sqlite handle"))
                .await?;
        }
        Backend::Postgres => {
            sqlx::query(&sql)
                .bind(approved_by.to_string())
                .bind(approver_trust)
                .bind(&now)
                .bind(id)
                .execute(db.postgres_pool().expect("postgres handle"))
                .await?;
        }
    }
    Ok(())
}

/// Append one recorded action, so a revert is a read of what happened.
///
/// Every mutation the merge performs records itself here. That is what makes
/// the reversal in §33.3(c) exact: `revert` reads these rows rather than
/// inferring what must have changed.
async fn record_action(
    db: &Database,
    proposal_id: &str,
    action: &str,
    previous_value: &str,
    subject_id: &str,
) -> Result<()> {
    let id = Uuid::new_v4().to_string();
    let now = crate::identity::now_rfc3339();
    let sql = db.sql(
        "INSERT INTO tag_wrangler_merge_actions
           (id, proposal_id, action, previous_value, subject_id, created_at)
         VALUES (?, ?, ?, ?, ?, ?)",
        "INSERT INTO tag_wrangler_merge_actions
           (id, proposal_id, action, previous_value, subject_id, created_at)
         VALUES (?::uuid, ?::uuid, ?, ?, ?, ?::timestamptz)",
    );
    match db.backend() {
        Backend::Sqlite => {
            sqlx::query(&sql)
                .bind(&id)
                .bind(proposal_id)
                .bind(action)
                .bind(previous_value)
                .bind(subject_id)
                .bind(&now)
                .execute(db.sqlite_pool().expect("sqlite handle"))
                .await?;
        }
        Backend::Postgres => {
            sqlx::query(&sql)
                .bind(&id)
                .bind(proposal_id)
                .bind(action)
                .bind(previous_value)
                .bind(subject_id)
                .bind(&now)
                .execute(db.postgres_pool().expect("postgres handle"))
                .await?;
        }
    }
    Ok(())
}

/// Apply a merge and record every row it moved.
///
/// The source node is never destroyed. A merge retargets the work tags and
/// aliases that pointed at it and leaves the node in place, so the history the
/// source carries survives and a revert is a matter of putting the tags back --
/// which is what `tag_wrangler_merge_actions` exists to make exact rather than
/// inferred.
async fn apply_merge(
    db: &Database,
    proposal_id: &str,
    from_node_id: &str,
    to_node_id: &str,
) -> Result<()> {
    // Record every tag that is about to move, with the node it came from and the
    // weight it had. The weight is part of what a revert has to restore: a tag
    // put back at the default would quietly change the reader's own view of how
    // strongly a work is a fantasy.
    let find_sql = db.sql(
        "SELECT work_id, weight FROM work_tags WHERE node_id = ?",
        "SELECT work_id::text AS work_id, weight FROM work_tags WHERE node_id = ?",
    );
    let tagged: Vec<(String, i64)> = match db.backend() {
        Backend::Sqlite => {
            sqlx::query_as(&find_sql)
                .bind(from_node_id)
                .fetch_all(db.sqlite_pool().expect("sqlite handle"))
                .await?
        }
        Backend::Postgres => {
            sqlx::query_as(&find_sql)
                .bind(from_node_id)
                .fetch_all(db.postgres_pool().expect("postgres handle"))
                .await?
        }
    };

    // Each tagged work is handled on its own rather than with one set-based
    // statement. The set-based form needs a correlated subquery over the table
    // being updated, and that does not behave the same way on both backends --
    // on SQLite the update moves rows the guard meant to skip, and the merge
    // reports success having changed nothing. Per row, the rule is the same
    // three lines on either backend and the difference between "moved" and
    // "already had it" stays visible, which is what the revert needs to know.
    let has_target_sql = db.sql(
        "SELECT COUNT(*) FROM work_tags WHERE work_id = ? AND node_id = ?",
        "SELECT COUNT(*)::bigint AS count FROM work_tags WHERE work_id = ?::uuid AND node_id = ?",
    );
    let move_sql = "UPDATE work_tags SET node_id = ? WHERE work_id = ? AND node_id = ?";
    let drop_sql = db.sql(
        "DELETE FROM work_tags WHERE work_id = ? AND node_id = ?",
        "DELETE FROM work_tags WHERE work_id = ?::uuid AND node_id = ?",
    );

    for (work_id, weight) in &tagged {
        let already: i64 = match db.backend() {
            Backend::Sqlite => {
                sqlx::query_as::<_, (i64,)>(&has_target_sql)
                    .bind(work_id)
                    .bind(to_node_id)
                    .fetch_one(db.sqlite_pool().expect("sqlite handle"))
                    .await?
                    .0
            }
            Backend::Postgres => {
                sqlx::query_as::<_, (i64,)>(&has_target_sql)
                    .bind(work_id)
                    .bind(to_node_id)
                    .fetch_one(db.postgres_pool().expect("postgres handle"))
                    .await?
                    .0
            }
        };

        if already == 0 {
            // The work did not carry the target, so the row simply moves and its
            // weight comes with it. Recorded as `retarget_tags` with the node it
            // came from, so a revert knows to point it back.
            record_action(db, proposal_id, "retarget_tags", from_node_id, work_id).await?;
            match db.backend() {
                Backend::Sqlite => {
                    sqlx::query(move_sql)
                        .bind(to_node_id)
                        .bind(work_id)
                        .bind(from_node_id)
                        .execute(db.sqlite_pool().expect("sqlite handle"))
                        .await?;
                }
                Backend::Postgres => {
                    sqlx::query(move_sql)
                        .bind(to_node_id)
                        .bind(work_id)
                        .bind(from_node_id)
                        .execute(db.postgres_pool().expect("postgres handle"))
                        .await?;
                }
            }
        } else {
            // The work already carried the target. Moving the row would create
            // a second row for the same pair, and leaving it would leave the
            // work tagged with both spellings -- which is the state the merge
            // exists to end. So the source row goes, its weight is recorded
            // first, and the revert puts it back with that weight.
            //
            // The source node itself is never deleted, so the history it
            // carries survives the merge.
            record_action(db, proposal_id, "retarget_tags", from_node_id, work_id).await?;
            record_action(db, proposal_id, "set_weight", &weight.to_string(), work_id).await?;
            match db.backend() {
                Backend::Sqlite => {
                    sqlx::query(&drop_sql)
                        .bind(work_id)
                        .bind(from_node_id)
                        .execute(db.sqlite_pool().expect("sqlite handle"))
                        .await?;
                }
                Backend::Postgres => {
                    sqlx::query(&drop_sql)
                        .bind(work_id)
                        .bind(from_node_id)
                        .execute(db.postgres_pool().expect("postgres handle"))
                        .await?;
                }
            }
        }
    }

    // Aliases follow the tags, and the same collision rule applies.
    // The same rule as the tags: an alias that already points at the target is
    // left alone, so a merge cannot create a second row for one spelling.
    let alias_sql = "UPDATE taxonomy_aliases
                        SET node_id = ?
                      WHERE node_id = ?
                        AND NOT EXISTS (SELECT 1 FROM taxonomy_aliases existing
                                         WHERE existing.alias = taxonomy_aliases.alias
                                           AND existing.node_id = ?)";
    match db.backend() {
        Backend::Sqlite => {
            sqlx::query(&alias_sql)
                .bind(to_node_id)
                .bind(from_node_id)
                .bind(to_node_id)
                .execute(db.sqlite_pool().expect("sqlite handle"))
                .await?;
        }
        Backend::Postgres => {
            sqlx::query(&alias_sql)
                .bind(to_node_id)
                .bind(from_node_id)
                .bind(to_node_id)
                .execute(db.postgres_pool().expect("postgres handle"))
                .await?;
        }
    }

    Ok(())
}

/// Revert an approved merge, restoring what it moved.
///
/// Reads the recorded actions and puts each subject back where it came from, so
/// the reversal is a read of what happened rather than a guess at what must
/// have happened. The proposal is marked `reverted` and chained to its own
/// successor, which is what §33.3's "merges keep their history" means in the
/// data.
pub async fn revert_wrangling(
    db: &Database,
    id: &str,
    reverted_by: Uuid,
    approver_trust: i64,
) -> Result<()> {
    let Some(proposal) = get_wrangling_proposal(db, id).await? else {
        return Err(WrangleError::NotFound.into());
    };
    if proposal.status != "approved" {
        return Err(WrangleError::WrongState("not approved").into());
    }
    let target = proposal.to_node_id.clone().unwrap_or_default();
    let reverted_at = crate::identity::now_rfc3339();

    // The recorded actions, in the order they happened. The reversal is a read
    // of these rows rather than an inference about what a merge must have
    // touched, which is the difference between a revert that is exact and one
    // that is plausible.
    let actions_sql = db.sql(
        "SELECT action, subject_id, previous_value FROM tag_wrangler_merge_actions
          WHERE proposal_id = ? AND reverted_at IS NULL
          ORDER BY created_at ASC, rowid ASC",
        "SELECT action, subject_id, previous_value FROM tag_wrangler_merge_actions
          WHERE proposal_id = ?::uuid AND reverted_at IS NULL
          ORDER BY created_at ASC, id ASC",
    );
    let actions: Vec<(String, Option<String>, Option<String>)> = match db.backend() {
        Backend::Sqlite => {
            sqlx::query_as(&actions_sql)
                .bind(id)
                .fetch_all(db.sqlite_pool().expect("sqlite handle"))
                .await?
        }
        Backend::Postgres => {
            sqlx::query_as(&actions_sql)
                .bind(id)
                .fetch_all(db.postgres_pool().expect("postgres handle"))
                .await?
        }
    };

    for (action, subject, previous) in &actions {
        let (Some(subject), Some(previous)) = (subject, previous) else {
            continue;
        };
        match action.as_str() {
            // The tag went from `previous` to the target. Put it back on
            // `previous` at the weight it had, recreating the row if the
            // dedupe step deleted it instead of moving it.
            "retarget_tags" => {
                let weight = actions
                    .iter()
                    .find(|(a, sub, _)| {
                        a == "set_weight" && sub.as_deref() == Some(subject.as_str())
                    })
                    .and_then(|(_, _, value)| value.as_deref())
                    .and_then(|v| v.parse::<i64>().ok())
                    .unwrap_or(0);
                let work_uuid = uuid::Uuid::parse_str(subject)
                    .map_err(|_| anyhow::anyhow!("recorded a non-uuid work id"))?;
                let previous_uuid = uuid::Uuid::parse_str(previous)
                    .map_err(|_| anyhow::anyhow!("recorded a non-uuid node id"))?;

                let restore_sql = db.sql(
                    "INSERT OR REPLACE INTO work_tags (work_id, node_id, weight, added_at) VALUES (?, ?, ?, ?)",
                    "INSERT INTO work_tags (work_id, node_id, weight, added_at) VALUES (?::uuid, ?::uuid, ?, ?::timestamptz)
                     ON CONFLICT (work_id, node_id) DO UPDATE SET weight = excluded.weight",
                );
                match db.backend() {
                    Backend::Sqlite => {
                        sqlx::query(&restore_sql)
                            .bind(subject)
                            .bind(previous)
                            .bind(weight)
                            .bind(&reverted_at)
                            .execute(db.sqlite_pool().expect("sqlite handle"))
                            .await?;
                    }
                    Backend::Postgres => {
                        sqlx::query(&restore_sql)
                            .bind(work_uuid)
                            .bind(previous_uuid)
                            .bind(weight)
                            .bind(&reverted_at)
                            .execute(db.postgres_pool().expect("postgres handle"))
                            .await?;
                    }
                }

                // The target row goes only if the merge created it. A recorded
                // `set_weight` beside this subject means the merge deleted the
                // source instead of moving it, which is what happens to a work
                // that already carried the target -- and that work must keep
                // that tag, because it had it before anyone merged anything.
                let had_target = actions.iter().any(|(a, sub, _)| {
                    a == "set_weight" && sub.as_deref() == Some(subject.as_str())
                });
                if !had_target {
                    let drop_sql = db.sql(
                        "DELETE FROM work_tags WHERE work_id = ? AND node_id = ?",
                        "DELETE FROM work_tags WHERE work_id = ?::uuid AND node_id = ?",
                    );
                    match db.backend() {
                        Backend::Sqlite => {
                            sqlx::query(&drop_sql)
                                .bind(subject)
                                .bind(&target)
                                .execute(db.sqlite_pool().expect("sqlite handle"))
                                .await?;
                        }
                        Backend::Postgres => {
                            sqlx::query(&drop_sql)
                                .bind(subject)
                                .bind(&target)
                                .execute(db.postgres_pool().expect("postgres handle"))
                                .await?;
                        }
                    }
                }
            }
            // The merge left the weight alone, so there is nothing to undo. The
            // row's weight was restored by the `retarget_tags` branch above.
            _ => {}
        }
    }

    let mark_sql = db.sql(
        "UPDATE tag_wrangler_merge_actions SET reverted_at = ? WHERE proposal_id = ? AND reverted_at IS NULL",
        "UPDATE tag_wrangler_merge_actions SET reverted_at = ?::timestamptz WHERE proposal_id = ?::uuid AND reverted_at IS NULL",
    );
    match db.backend() {
        Backend::Sqlite => {
            sqlx::query(&mark_sql)
                .bind(&reverted_at)
                .bind(id)
                .execute(db.sqlite_pool().expect("sqlite handle"))
                .await?;
        }
        Backend::Postgres => {
            sqlx::query(&mark_sql)
                .bind(&reverted_at)
                .bind(id)
                .execute(db.postgres_pool().expect("postgres handle"))
                .await?;
        }
    }

    // A new proposal records the reversal, so the chain is auditable and the
    // original approval still reads as approved rather than being rewritten.
    let reversal = propose_wrangling(
        db,
        proposal.kind,
        &target,
        Some(&proposal.from_node_id),
        &format!("reverts {id}"),
        reverted_by,
        approver_trust,
    )
    .await?;
    let chain_sql = db.sql(
        "UPDATE tag_wrangling_proposals SET status = 'reverted', reverts_id = ? WHERE id = ?",
        "UPDATE tag_wrangling_proposals SET status = 'reverted', reverts_id = ?::uuid WHERE id = ?::uuid",
    );
    match db.backend() {
        Backend::Sqlite => {
            sqlx::query(&chain_sql)
                .bind(&reversal)
                .bind(id)
                .execute(db.sqlite_pool().expect("sqlite handle"))
                .await?;
        }
        Backend::Postgres => {
            sqlx::query(&chain_sql)
                .bind(&reversal)
                .bind(id)
                .execute(db.postgres_pool().expect("postgres handle"))
                .await?;
        }
    }
    Ok(())
}

/// misleads exactly as badly as no log.
pub async fn public_wrangling_log(db: &Database, limit: i64) -> Result<Vec<WranglingProposal>> {
    let sql = db.sql(
        "SELECT id, kind, from_node_id, to_node_id, reason, status,
                proposer_trust, approver_trust, created_at
           FROM tag_wrangling_proposals
          WHERE status IN ('approved', 'reverted')
          ORDER BY created_at DESC, id DESC LIMIT ?",
        "SELECT id::text, kind, from_node_id, to_node_id, reason, status,
                proposer_trust::bigint AS proposer_trust, approver_trust::bigint AS approver_trust,
                created_at::text AS created_at
           FROM tag_wrangling_proposals
          WHERE status IN ('approved', 'reverted')
          ORDER BY created_at DESC, id DESC LIMIT ?",
    );
    let rows: Vec<(
        String,
        String,
        String,
        Option<String>,
        String,
        String,
        i64,
        Option<i64>,
        String,
    )> = match db.backend() {
        Backend::Sqlite => {
            sqlx::query_as(&sql)
                .bind(limit)
                .fetch_all(db.sqlite_pool().expect("sqlite handle"))
                .await?
        }
        Backend::Postgres => {
            sqlx::query_as(&sql)
                .bind(limit)
                .fetch_all(db.postgres_pool().expect("postgres handle"))
                .await?
        }
    };
    Ok(rows
        .into_iter()
        .map(
            |(id, kind, from, to, reason, status, ptrust, atrust, created_at)| WranglingProposal {
                id,
                kind: WranglingKind::parse(&kind).unwrap_or(WranglingKind::Alias),
                from_node_id: from,
                to_node_id: to,
                reason,
                status,
                proposer_trust: ptrust,
                approver_trust: atrust,
                created_at,
            },
        )
        .collect())
}

#[cfg(test)]
mod tests {
    use super::*;
    use lorehaven_domain::recommendation_transparency::SlotReason;

    #[test]
    fn a_record_serializes_its_reasons_as_the_vocabulary_wire_forms() {
        // The persisted shape is what a future version has to read, so it is
        // pinned here rather than left to the SQL.
        let rec = SlotRecord {
            pseud_id: Uuid::nil(),
            work_id: Uuid::nil(),
            request_id: Uuid::nil(),
            position: 0,
            reasons: vec![SlotReason::TasteTags, SlotReason::Popular],
            taste_signal: Some(TasteSignal::Strong),
            seeded_by: None,
            recipe_stage: None,
            instance_curation: InstanceCuration::NotInvolved,
            blend_score: 0,
        };
        let json =
            serde_json::to_string(&rec.reasons.iter().map(|r| r.as_str()).collect::<Vec<_>>())
                .expect("serialize");
        assert_eq!(json, r#"["taste_tags","popular"]"#);
    }

    #[test]
    fn an_unknown_reason_stored_in_a_row_is_dropped_not_rendered() {
        // This is what `explain_slot` does with a reason it cannot parse.
        let stored = vec!["taste_tags".to_string(), "operator_boost".to_string()];
        let parsed: Vec<SlotReason> = stored.iter().filter_map(|s| SlotReason::parse(s)).collect();
        assert_eq!(parsed, vec![SlotReason::TasteTags]);
    }

    #[test]
    fn a_corrupt_reasons_column_degrades_to_no_reasons() {
        // A row whose JSON is not an array must not 500 the explanation door.
        let parsed: Vec<SlotReason> = serde_json::from_str::<Vec<String>>("{not json")
            .unwrap_or_default()
            .iter()
            .filter_map(|s| SlotReason::parse(s))
            .collect();
        assert!(parsed.is_empty());
    }
}
