[package]
name = "test-support"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
uuid.workspace = true
axum.workspace = true
lorehaven-db = { path = "../db" }
serde_json.workspace = true
sqlx = { workspace = true }
tokio = { workspace = true, features = ["rt", "macros"] }
tower.workspace = true
tracing-subscriber.workspace = true
